[package]
name = "wgatools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
nom = "7.1.3"
serde = {version = "1.0.166", features = ["derive"]}

[lib]
name = "wgalib"
path = "src/lib.rs"

[[bin]]
name = "wgatools"
path = "src/main.rs"
